USE [master]
GO
/****** Object:  Database [DaimlerDB]    Script Date: 14/12/2019 14:45:03 ******/
CREATE DATABASE [DaimlerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DaimlerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DaimlerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DaimlerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DaimlerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DaimlerDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DaimlerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DaimlerDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DaimlerDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DaimlerDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DaimlerDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DaimlerDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DaimlerDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DaimlerDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DaimlerDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DaimlerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DaimlerDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DaimlerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DaimlerDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DaimlerDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DaimlerDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DaimlerDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DaimlerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DaimlerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DaimlerDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DaimlerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DaimlerDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DaimlerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DaimlerDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DaimlerDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DaimlerDB] SET  MULTI_USER 
GO
ALTER DATABASE [DaimlerDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DaimlerDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DaimlerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DaimlerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DaimlerDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DaimlerDB] SET QUERY_STORE = OFF
GO
USE [DaimlerDB]
GO
/****** Object:  Table [dbo].[UserInformation]    Script Date: 14/12/2019 14:45:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserInformation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ApplicationName] [varchar](50) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
 CONSTRAINT [PK_UserInformation] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[UserInformation] ON 
GO
INSERT [dbo].[UserInformation] ([Id], [ApplicationName], [UserName], [Email]) VALUES (1, N'GO', N'akanmf', N'akanmf@yahoo.com')
GO
INSERT [dbo].[UserInformation] ([Id], [ApplicationName], [UserName], [Email]) VALUES (2, N'GEMS', N'barang', N'barang@gmail.com')
GO
INSERT [dbo].[UserInformation] ([Id], [ApplicationName], [UserName], [Email]) VALUES (3, N'AUTOLINE', N'eskicig', N'eskicig@hotmail.com')
GO
SET IDENTITY_INSERT [dbo].[UserInformation] OFF
GO
USE [master]
GO
ALTER DATABASE [DaimlerDB] SET  READ_WRITE 
GO
